<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>FocusOverlay</RootNamespace>
    <AssemblyName>FocusOverlay</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\eye.ico</ApplicationIcon>
    <Version>1.2.0</Version>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\eye.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.37.0" />
  </ItemGroup>

</Project>
