//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusOverlay.Properties {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FocusOverlay.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay is already running — look for its tray icon..
        /// </summary>
        public static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay — error.
        /// </summary>
        public static string AppErrorTitle {
            get {
                return ResourceManager.GetString("AppErrorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to read manifest.json.
        /// </summary>
        public static string ArchiveCannotReadManifest {
            get {
                return ResourceManager.GetString("ArchiveCannotReadManifest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay backup (*.foverlay-backup;*.zip)|*.foverlay....
        /// </summary>
        public static string BackupDialogFilter {
            get {
                return ResourceManager.GetString("BackupDialogFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The backup was created by a newer version (format v{0}).
        /// </summary>
        public static string BackupNewerVersion {
            get {
                return ResourceManager.GetString("BackupNewerVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The backup does not contain settings.json.
        /// </summary>
        public static string BackupNoSettings {
            get {
                return ResourceManager.GetString("BackupNoSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file is not a Focus Overlay backup.
        /// </summary>
        public static string BackupNotBackup {
            get {
                return ResourceManager.GetString("BackupNotBackup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string ColorPickerAfter {
            get {
                return ResourceManager.GetString("ColorPickerAfter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string ColorPickerBefore {
            get {
                return ResourceManager.GetString("ColorPickerBefore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string ColorPickerPreviewHeading {
            get {
                return ResourceManager.GetString("ColorPickerPreviewHeading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sample overlay text.
        /// </summary>
        public static string ColorPickerPreviewText {
            get {
                return ResourceManager.GetString("ColorPickerPreviewText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pick a color.
        /// </summary>
        public static string ColorPickerTooltip {
            get {
                return ResourceManager.GetString("ColorPickerTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CommonClose {
            get {
                return ResourceManager.GetString("CommonClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export….
        /// </summary>
        public static string CommonExport {
            get {
                return ResourceManager.GetString("CommonExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import….
        /// </summary>
        public static string CommonImport {
            get {
                return ResourceManager.GetString("CommonImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import all….
        /// </summary>
        public static string CommonImportAll {
            get {
                return ResourceManager.GetString("CommonImportAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string CommonPreset {
            get {
                return ResourceManager.GetString("CommonPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset position and zoom.
        /// </summary>
        public static string CommonResetUserView {
            get {
                return ResourceManager.GetString("CommonResetUserView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings….
        /// </summary>
        public static string CommonSettings {
            get {
                return ResourceManager.GetString("CommonSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show / hide.
        /// </summary>
        public static string CommonToggle {
            get {
                return ResourceManager.GetString("CommonToggle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string CommonUntitled {
            get {
                return ResourceManager.GetString("CommonUntitled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to save the backup:.
        /// </summary>
        public static string ControllerExportBackupFailed {
            get {
                return ResourceManager.GetString("ControllerExportBackupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export settings and all presets.
        /// </summary>
        public static string ControllerExportBackupTitle {
            get {
                return ResourceManager.GetString("ControllerExportBackupTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export the preset:.
        /// </summary>
        public static string ControllerExportPresetFailed {
            get {
                return ResourceManager.GetString("ControllerExportPresetFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export preset.
        /// </summary>
        public static string ControllerExportPresetTitle {
            get {
                return ResourceManager.GetString("ControllerExportPresetTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to export settings:.
        /// </summary>
        public static string ControllerExportSettingsFailed {
            get {
                return ResourceManager.GetString("ControllerExportSettingsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string ControllerExportSettingsTitle {
            get {
                return ResourceManager.GetString("ControllerExportSettingsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotkeys are in use.
        /// </summary>
        public static string ControllerHotkeysBusy {
            get {
                return ResourceManager.GetString("ControllerHotkeysBusy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load the backup:.
        /// </summary>
        public static string ControllerImportBackupFailed {
            get {
                return ResourceManager.GetString("ControllerImportBackupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace current presets with the presets from the backup?.
        /// </summary>
        public static string ControllerImportBackupQuestion {
            get {
                return ResourceManager.GetString("ControllerImportBackupQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import settings and all presets.
        /// </summary>
        public static string ControllerImportBackupTitle {
            get {
                return ResourceManager.GetString("ControllerImportBackupTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Folder with .md files.
        /// </summary>
        public static string ControllerImportFolderTitle {
            get {
                return ResourceManager.GetString("ControllerImportFolderTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preset “{0}” was imported, but it has errors:.
        /// </summary>
        public static string ControllerImportIssues {
            get {
                return ResourceManager.GetString("ControllerImportIssues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to import the preset:.
        /// </summary>
        public static string ControllerImportPresetFailed {
            get {
                return ResourceManager.GetString("ControllerImportPresetFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import preset.
        /// </summary>
        public static string ControllerImportPresetTitle {
            get {
                return ResourceManager.GetString("ControllerImportPresetTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to import settings:.
        /// </summary>
        public static string ControllerImportSettingsFailed {
            get {
                return ResourceManager.GetString("ControllerImportSettingsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        public static string ControllerImportSettingsTitle {
            get {
                return ResourceManager.GetString("ControllerImportSettingsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to “{0}” — {1}.
        /// </summary>
        public static string ControllerIssueInPage {
            get {
                return ResourceManager.GetString("ControllerIssueInPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ControllerIssuesMore {
            get {
                return ResourceManager.GetString("ControllerIssuesMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to register hotkeys:.
        /// </summary>
        public static string ControllerRegisterHotkeysFailed {
            get {
                return ResourceManager.GetString("ControllerRegisterHotkeysFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save error.
        /// </summary>
        public static string ControllerSaveError {
            get {
                return ResourceManager.GetString("ControllerSaveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom center.
        /// </summary>
        public static string CornerBottomCenter {
            get {
                return ResourceManager.GetString("CornerBottomCenter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        public static string CornerBottomLeft {
            get {
                return ResourceManager.GetString("CornerBottomLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        public static string CornerBottomRight {
            get {
                return ResourceManager.GetString("CornerBottomRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top center.
        /// </summary>
        public static string CornerTopCenter {
            get {
                return ResourceManager.GetString("CornerTopCenter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        public static string CornerTopLeft {
            get {
                return ResourceManager.GetString("CornerTopLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        public static string CornerTopRight {
            get {
                return ResourceManager.GetString("CornerTopRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to color: #RRGGBB, #AARRGGBB or a name.
        /// </summary>
        public static string DiagExpectedColor {
            get {
                return ResourceManager.GetString("DiagExpectedColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to top-left, top-center, top-right, bottom-left, bottom-cent....
        /// </summary>
        public static string DiagExpectedCorner {
            get {
                return ResourceManager.GetString("DiagExpectedCorner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to a number from 6 to 48.
        /// </summary>
        public static string DiagExpectedFontSize {
            get {
                return ResourceManager.GetString("DiagExpectedFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.5 or 50%.
        /// </summary>
        public static string DiagExpectedOpacity {
            get {
                return ResourceManager.GetString("DiagExpectedOpacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to a number of pixels.
        /// </summary>
        public static string DiagExpectedPixels {
            get {
                return ResourceManager.GetString("DiagExpectedPixels", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to a number greater than 0, e.g. 1.2.
        /// </summary>
        public static string DiagExpectedPositive {
            get {
                return ResourceManager.GetString("DiagExpectedPositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to image file is not specified.
        /// </summary>
        public static string DiagImageNoFile {
            get {
                return ResourceManager.GetString("DiagImageNoFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to image not found: {0}.
        /// </summary>
        public static string DiagImageNotFound {
            get {
                return ResourceManager.GetString("DiagImageNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to space in image path “{0}”: replace spaces with %20 or use....
        /// </summary>
        public static string DiagImagePathSpace {
            get {
                return ResourceManager.GetString("DiagImagePathSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to invalid value “{0}” for “{1}”, expected {2}.
        /// </summary>
        public static string DiagInvalidValue {
            get {
                return ResourceManager.GetString("DiagInvalidValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Line {0}: {1}.
        /// </summary>
        public static string DiagLine {
            get {
                return ResourceManager.GetString("DiagLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to file is not an image: {0}.
        /// </summary>
        public static string DiagNotImage {
            get {
                return ResourceManager.GetString("DiagNotImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to line “{0}” is not in “parameter: value” format.
        /// </summary>
        public static string DiagNotKeyValue {
            get {
                return ResourceManager.GetString("DiagNotKeyValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to system.md only uses ```{0} blocks, everything else is ign....
        /// </summary>
        public static string DiagSystemOnlyBlocks {
            get {
                return ResourceManager.GetString("DiagSystemOnlyBlocks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to unknown parameter “{0}”.
        /// </summary>
        public static string DiagUnknownParameter {
            get {
                return ResourceManager.GetString("DiagUnknownParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to add the image:.
        /// </summary>
        public static string EditorAddImageFailed {
            get {
                return ResourceManager.GetString("EditorAddImageFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add image.
        /// </summary>
        public static string EditorAddImageTitle {
            get {
                return ResourceManager.GetString("EditorAddImageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add tab.
        /// </summary>
        public static string EditorAddPage {
            get {
                return ResourceManager.GetString("EditorAddPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You can't delete the only preset..
        /// </summary>
        public static string EditorCannotDeleteLastPreset {
            get {
                return ResourceManager.GetString("EditorCannotDeleteLastPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string EditorDelete {
            get {
                return ResourceManager.GetString("EditorDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete tab “{0}”?.
        /// </summary>
        public static string EditorDeletePageConfirm {
            get {
                return ResourceManager.GetString("EditorDeletePageConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete preset “{0}” along with its images?.
        /// </summary>
        public static string EditorDeletePresetConfirm {
            get {
                return ResourceManager.GetString("EditorDeletePresetConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Images|*.png;*.jpg;*.jpeg;*.gif;*.bmp;*.webp;*.tif;*.tiff....
        /// </summary>
        public static string EditorImageFilter {
            get {
                return ResourceManager.GetString("EditorImageFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import folder….
        /// </summary>
        public static string EditorImportFolder {
            get {
                return ResourceManager.GetString("EditorImportFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image….
        /// </summary>
        public static string EditorInsertImage {
            get {
                return ResourceManager.GetString("EditorInsertImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Double-click to go to the line.
        /// </summary>
        public static string EditorIssuesTooltip {
            get {
                return ResourceManager.GetString("EditorIssuesTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string EditorMoveDown {
            get {
                return ResourceManager.GetString("EditorMoveDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string EditorMoveUp {
            get {
                return ResourceManager.GetString("EditorMoveUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string EditorNameLabel {
            get {
                return ResourceManager.GetString("EditorNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string EditorNew {
            get {
                return ResourceManager.GetString("EditorNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to paste the image:.
        /// </summary>
        public static string EditorPasteImageFailed {
            get {
                return ResourceManager.GetString("EditorPasteImageFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preset:.
        /// </summary>
        public static string EditorPresetLabel {
            get {
                return ResourceManager.GetString("EditorPresetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove tab.
        /// </summary>
        public static string EditorRemovePage {
            get {
                return ResourceManager.GetString("EditorRemovePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to system.md — overlay appearance for the whole preset. Only....
        /// </summary>
        public static string EditorSystemHint {
            get {
                return ResourceManager.GetString("EditorSystemHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ⚙ system.md — preset settings.
        /// </summary>
        public static string EditorSystemTab {
            get {
                return ResourceManager.GetString("EditorSystemTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ```focus-overlay block for the whole preset. This tab is ....
        /// </summary>
        public static string EditorSystemTabTooltip {
            get {
                return ResourceManager.GetString("EditorSystemTabTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string EditorTitleLabel {
            get {
                return ResourceManager.GetString("EditorTitleLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move overlay down.
        /// </summary>
        public static string HotkeyMoveBottom {
            get {
                return ResourceManager.GetString("HotkeyMoveBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Center overlay.
        /// </summary>
        public static string HotkeyMoveCenter {
            get {
                return ResourceManager.GetString("HotkeyMoveCenter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move overlay left.
        /// </summary>
        public static string HotkeyMoveLeft {
            get {
                return ResourceManager.GetString("HotkeyMoveLeft", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move overlay right.
        /// </summary>
        public static string HotkeyMoveRight {
            get {
                return ResourceManager.GetString("HotkeyMoveRight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move overlay up.
        /// </summary>
        public static string HotkeyMoveTop {
            get {
                return ResourceManager.GetString("HotkeyMoveTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next tab.
        /// </summary>
        public static string HotkeyNextPage {
            get {
                return ResourceManager.GetString("HotkeyNextPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next preset.
        /// </summary>
        public static string HotkeyNextPreset {
            get {
                return ResourceManager.GetString("HotkeyNextPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous tab.
        /// </summary>
        public static string HotkeyPrevPage {
            get {
                return ResourceManager.GetString("HotkeyPrevPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous preset.
        /// </summary>
        public static string HotkeyPrevPreset {
            get {
                return ResourceManager.GetString("HotkeyPrevPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to register (used by another program?): {0}.
        /// </summary>
        public static string HotkeyRegisterFailedInline {
            get {
                return ResourceManager.GetString("HotkeyRegisterFailedInline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scroll down.
        /// </summary>
        public static string HotkeyScrollDown {
            get {
                return ResourceManager.GetString("HotkeyScrollDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scroll up.
        /// </summary>
        public static string HotkeyScrollUp {
            get {
                return ResourceManager.GetString("HotkeyScrollUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string HotkeyZoomIn {
            get {
                return ResourceManager.GetString("HotkeyZoomIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string HotkeyZoomOut {
            get {
                return ResourceManager.GetString("HotkeyZoomOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageNameEnglish {
            get {
                return ResourceManager.GetString("LanguageNameEnglish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string LanguageNameRussian {
            get {
                return ResourceManager.GetString("LanguageNameRussian", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        public static string ModelNewPage {
            get {
                return ResourceManager.GetString("ModelNewPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New preset.
        /// </summary>
        public static string ModelNewPreset {
            get {
                return ResourceManager.GetString("ModelNewPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tab {0}.
        /// </summary>
        public static string ModelPageNumbered {
            get {
                return ResourceManager.GetString("ModelPageNumbered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to # Focus Overlay.
        /// </summary>
        public static string ModelSampleContent {
            get {
                return ResourceManager.GetString("ModelSampleContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string ModelSamplePreset {
            get {
                return ResourceManager.GetString("ModelSamplePreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to *No tabs — add them in the editor (double-click the tray ....
        /// </summary>
        public static string OverlayNoPages {
            get {
                return ResourceManager.GetString("OverlayNoPages", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The archive contains neither manifest.json nor .md files.
        /// </summary>
        public static string PresetArchiveEmpty {
            get {
                return ResourceManager.GetString("PresetArchiveEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The archive does not contain {0}.
        /// </summary>
        public static string PresetArchiveMissingEntry {
            get {
                return ResourceManager.GetString("PresetArchiveMissingEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overlay preset (*.foverlay;*.zip)|*.foverlay;*.zip|All fi....
        /// </summary>
        public static string PresetDialogFilter {
            get {
                return ResourceManager.GetString("PresetDialogFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The folder contains no .md files.
        /// </summary>
        public static string PresetFolderNoMarkdown {
            get {
                return ResourceManager.GetString("PresetFolderNoMarkdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The preset was created by a newer version (format v{0}).
        /// </summary>
        public static string PresetNewerVersion {
            get {
                return ResourceManager.GetString("PresetNewerVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The archive is not a Focus Overlay preset.
        /// </summary>
        public static string PresetNotPreset {
            get {
                return ResourceManager.GetString("PresetNotPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string SettingsAccentColor {
            get {
                return ResourceManager.GetString("SettingsAccentColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active tab color.
        /// </summary>
        public static string SettingsActiveTabColor {
            get {
                return ResourceManager.GetString("SettingsActiveTabColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string SettingsAppearance {
            get {
                return ResourceManager.GetString("SettingsAppearance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Background opacity.
        /// </summary>
        public static string SettingsBackgroundOpacity {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings + all presets.
        /// </summary>
        public static string SettingsBackupGroup {
            get {
                return ResourceManager.GetString("SettingsBackupGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay settings (*.json)|*.json|All files (*.*)|*.*.
        /// </summary>
        public static string SettingsDialogFilter {
            get {
                return ResourceManager.GetString("SettingsDialogFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export all….
        /// </summary>
        public static string SettingsExportAll {
            get {
                return ResourceManager.GetString("SettingsExportAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save settings only (.json).
        /// </summary>
        public static string SettingsExportTooltip {
            get {
                return ResourceManager.GetString("SettingsExportTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file is empty.
        /// </summary>
        public static string SettingsFileEmpty {
            get {
                return ResourceManager.GetString("SettingsFileEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string SettingsFontSize {
            get {
                return ResourceManager.GetString("SettingsFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string SettingsHeight {
            get {
                return ResourceManager.GetString("SettingsHeight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click a field and press a key combination. Backspace — cl....
        /// </summary>
        public static string SettingsHotkeysHint {
            get {
                return ResourceManager.GetString("SettingsHotkeysHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Load settings only (.json).
        /// </summary>
        public static string SettingsImportTooltip {
            get {
                return ResourceManager.GetString("SettingsImportTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The language will change after a restart. Restart now?.
        /// </summary>
        public static string SettingsLanguageRestart {
            get {
                return ResourceManager.GetString("SettingsLanguageRestart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string SettingsLanguageSystem {
            get {
                return ResourceManager.GetString("SettingsLanguageSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The settings were created by a newer version (format v{0}).
        /// </summary>
        public static string SettingsNewerVersion {
            get {
                return ResourceManager.GetString("SettingsNewerVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file is not Focus Overlay settings.
        /// </summary>
        public static string SettingsNotSettings {
            get {
                return ResourceManager.GetString("SettingsNotSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to X offset.
        /// </summary>
        public static string SettingsOffsetX {
            get {
                return ResourceManager.GetString("SettingsOffsetX", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Y offset.
        /// </summary>
        public static string SettingsOffsetY {
            get {
                return ResourceManager.GetString("SettingsOffsetY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string SettingsPosition {
            get {
                return ResourceManager.GetString("SettingsPosition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset position, appearance and hotkeys to defaults?.
        /// </summary>
        public static string SettingsResetConfirm {
            get {
                return ResourceManager.GetString("SettingsResetConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Screen corner.
        /// </summary>
        public static string SettingsScreenCorner {
            get {
                return ResourceManager.GetString("SettingsScreenCorner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string SettingsTabHotkeys {
            get {
                return ResourceManager.GetString("SettingsTabHotkeys", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string SettingsTabOverlay {
            get {
                return ResourceManager.GetString("SettingsTabOverlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When unchecked, the strip sits in the overlay corner, mat....
        /// </summary>
        public static string SettingsTabStripAttachedHint {
            get {
                return ResourceManager.GetString("SettingsTabStripAttachedHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Separate position (don't attach to the overlay).
        /// </summary>
        public static string SettingsTabStripDetached {
            get {
                return ResourceManager.GetString("SettingsTabStripDetached", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show tab strip.
        /// </summary>
        public static string SettingsTabStripVisible {
            get {
                return ResourceManager.GetString("SettingsTabStripVisible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom (×).
        /// </summary>
        public static string SettingsTabStripZoom {
            get {
                return ResourceManager.GetString("SettingsTabStripZoom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiplier of the overlay zoom: zoom hotkeys change the s....
        /// </summary>
        public static string SettingsTabStripZoomTooltip {
            get {
                return ResourceManager.GetString("SettingsTabStripZoomTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tab strip.
        /// </summary>
        public static string SettingsTabTabStrip {
            get {
                return ResourceManager.GetString("SettingsTabTabStrip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string SettingsTextColor {
            get {
                return ResourceManager.GetString("SettingsTextColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string SettingsWidth {
            get {
                return ResourceManager.GetString("SettingsWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string SettingsZoom {
            get {
                return ResourceManager.GetString("SettingsZoom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editor….
        /// </summary>
        public static string TrayEditor {
            get {
                return ResourceManager.GetString("TrayEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export all (settings + presets)….
        /// </summary>
        public static string TrayExportAll {
            get {
                return ResourceManager.GetString("TrayExportAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export current preset….
        /// </summary>
        public static string TrayExportPreset {
            get {
                return ResourceManager.GetString("TrayExportPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import .md folder….
        /// </summary>
        public static string TrayImportFolder {
            get {
                return ResourceManager.GetString("TrayImportFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import preset….
        /// </summary>
        public static string TrayImportPreset {
            get {
                return ResourceManager.GetString("TrayImportPreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open data folder.
        /// </summary>
        public static string TrayOpenDataFolder {
            get {
                return ResourceManager.GetString("TrayOpenDataFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay — editor.
        /// </summary>
        public static string WindowTitleEditor {
            get {
                return ResourceManager.GetString("WindowTitleEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay — settings.
        /// </summary>
        public static string WindowTitleSettings {
            get {
                return ResourceManager.GetString("WindowTitleSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay — tabs.
        /// </summary>
        public static string WindowTitleTabStrip {
            get {
                return ResourceManager.GetString("WindowTitleTabStrip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import ▾.
        /// </summary>
        public static string EditorImportMenu {
            get {
                return ResourceManager.GetString("EditorImportMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preset archive….
        /// </summary>
        public static string EditorImportArchive {
            get {
                return ResourceManager.GetString("EditorImportArchive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string EditorData {
            get {
                return ResourceManager.GetString("EditorData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open the folder with preset files.
        /// </summary>
        public static string EditorDataTooltip {
            get {
                return ResourceManager.GetString("EditorDataTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tab settings.
        /// </summary>
        public static string EditorPageSettings {
            get {
                return ResourceManager.GetString("EditorPageSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty field — the value is taken from the preset and app set...
        /// </summary>
        public static string EditorPageSettingsHint {
            get {
                return ResourceManager.GetString("EditorPageSettingsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        public static string EditorInherited {
            get {
                return ResourceManager.GetString("EditorInherited", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string EditorClearValue {
            get {
                return ResourceManager.GetString("EditorClearValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiplier to the scale of previous levels: 1.2 — 20% larger.
        /// </summary>
        public static string EditorScaleTooltip {
            get {
                return ResourceManager.GetString("EditorScaleTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0.5 or 50%.
        /// </summary>
        public static string EditorOpacityTooltip {
            get {
                return ResourceManager.GetString("EditorOpacityTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string EditorIssuesTitle {
            get {
                return ResourceManager.GetString("EditorIssuesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No errors.
        /// </summary>
        public static string EditorNoIssues {
            get {
                return ResourceManager.GetString("EditorNoIssues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markup reference.
        /// </summary>
        public static string EditorMarkupHelp {
            get {
                return ResourceManager.GetString("EditorMarkupHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus Overlay — markup.
        /// </summary>
        public static string WindowTitleMarkup {
            get {
                return ResourceManager.GetString("WindowTitleMarkup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to open the data folder: {0}.
        /// </summary>
        public static string ControllerOpenDataFailed {
            get {
                return ResourceManager.GetString("ControllerOpenDataFailed", resourceCulture);
            }
        }
    }
}
